### ISSUE TITLE
举报举报~哈哈哈

### ISSUE THREAD

**Issue by jardenliu** [justjavac/auto-green#1]
然后偷偷fork 一下

**Comment by schizobulia** [comment]
夜已沉默 心事向谁说 :joy:

**Comment by brizer** [comment]
意义不大，博君一笑

**Comment by Jaggle** [comment]
哈哈，我也做了类似的 jio 本~~，区别是可以填补过往（甚至未来的提交记录），自动各种绿色（狗头），忍不住 ad 一下：https://github.com/Jaggle/Gitfool
