### ISSUE TITLE
不是，有必要吗，github就是被你们这群人带偏的

### ISSUE THREAD

**Issue by xuyh1024** [justjavac/auto-green#156]
给认真搞技术的留一片净土把，求求了

**Comment by imkodo** [comment]
当成贴吧打卡了

**Comment by CC11001100** [comment]
v2传送门： https://v2ex.com/t/961701#reply35

—————— 来自海淀区吃瓜群众

**Comment by piexlmax** [comment]
issue可以被删除奥，建议发pr，删不了。

**Comment by justjavac** [comment]
我只是提供了一个工具，用不用在你们。（PS：反正我没用😂）
