### ISSUE TITLE
Actions被禁用，请问是否有腾讯云函数的版本？

### ISSUE THREAD

**Issue by BonjourYY** [justjavac/auto-green#17]
目前大部分人的GitHub Actions都被官方禁用了，作者是否可以写一个腾讯云函数的版本呢？

**Comment by justjavac** [comment]
理由是什么？滥用 GitHub Actions 吗？

**Comment by justjavac** [comment]
@BonjourYY 我写了一个 npm 包，可用于腾讯云函数的 node runtime

https://github.com/justjavac/node-auto-green
