### ISSUE TITLE
目前设置好了 但不能自己github action

### ISSUE THREAD

**Issue by Fitye** [justjavac/auto-green#21]

**Comment by justjavac** [comment]
我看了你的仓库，不要 fork

**Comment by Fitye** [comment]
> 我看了你的仓库，不要 fork
![image](https://user-images.githubusercontent.com/63393725/124542499-0f4a1880-de56-11eb-85e2-1d15c9bb3c36.png)
![image](https://user-images.githubusercontent.com/63393725/124542525-1b35da80-de56-11eb-9f57-3415b2fde25d.png)
那个fork的仓库是测试的 不是fork的只有这俩个手动触发的action

**Comment by justjavac** [comment]
```yml
  # schedule:
  #   - cron: "*/15 * * * *"
```

把前面的 `#` 去掉

**Comment by Fitye** [comment]
问题已经将解决，issue 已close
