### ISSUE TITLE
好像不起作用了，定时任务没执行。

### ISSUE THREAD

**Issue by ZeeMenng** [justjavac/auto-green#26]
改完定时任务，提交文件时就执行一次，之后就不再执行了。

**Comment by justjavac** [comment]
你的语法有问题，我帮你修复了 https://github.com/ZeeMenng/AutoGreen/pull/1

**Comment by ZeeMenng** [comment]
> 你的语法有问题，我帮你修复了 [ZeeMenng/AutoGreen#1](https://github.com/ZeeMenng/AutoGreen/pull/1)

感谢 后面可以愉快而又轻松的装逼了
