### ISSUE TITLE
会自动提交，但是不绿了

### ISSUE THREAD

**Issue by selierlin** [justjavac/auto-green#32]
会自动提交，但是不绿了，奇怪

**Comment by justjavac** [comment]
你的 name 或者 email 设置的不正确

https://github.com/selierlin/auto-green/blob/master/.github/workflows/ci.yml#L19-L20

**Comment by justjavac** [comment]
我提了一个 pr https://github.com/selierlin/auto-green/pull/1 帮你修复了
