### ISSUE TITLE
你们还能用吗 为什么我的突然运行失败

### ISSUE THREAD

**Issue by CatNiangFeitu** [justjavac/auto-green#49]
今天晚上 突然收到github发的邮件
![image](https://user-images.githubusercontent.com/108512490/204566831-d1fab570-75f6-42b0-9b53-92c74ac4d7a8.png)
![image](https://user-images.githubusercontent.com/108512490/204566589-e7ffd94b-8fab-4319-aebb-7e096e41e34c.png)
打开一看发现用不了了
排除是语法错误以及设置错误  因为之前正常运行了几个星期都没问题
我试着重新提交代码看能不能正常运行 但换来的是依然无法运行

**Comment by justjavac** [comment]
你的仓库删除了吗，没看到你的这个仓库啊

**Comment by CatNiangFeitu** [comment]
> 你的仓库删除了吗，没看到你的这个仓库啊

没有删除 不过说来也怪 目前仓库自己神奇的恢复了(期间没有动过任何设置)
