### ISSUE TITLE
能不能自动发 pr 到这里来

### ISSUE THREAD

**Issue by huobazi** [justjavac/auto-green#7]
好玩

```
曾经保持了 200 多天全绿，但是冷落了女朋友，一直绿到现在。
````

![image](https://user-images.githubusercontent.com/341526/103078905-cd6e2900-460d-11eb-8ca3-ac44c3c19bd4.png)
O(∩_∩)O哈哈~

**Comment by justjavac** [comment]
哈哈哈哈哈哈哈哈哈哈
