### ISSUE TITLE
你好，用不了了吗

### ISSUE THREAD

**Issue by wuhu201314** [justjavac/auto-green#72]
9
Already up to date.
10
[main c0eb56b] a commit a day keeps your girlfriend away
11
remote: Permission to wuhu201314/auto-green.git denied to github-actions[bot].
12
fatal: unable to access 'https://github.com/wuhu201314/auto-green/': The requested URL returned error: 403
13
Error: Process completed with exit code 128.

**Comment by justjavac** [comment]
看使用说明的第一条：

**点右上角 Use this template 按钮复制本 GitHub 仓库，⚠️ 千万不要 Fork，因为 fork 项目的动态并不会让你变绿 ⚠️**
