### ISSUE TITLE
你好我不是用的foke，但是一直运行失败

### ISSUE THREAD

**Issue by wuhu201314** [justjavac/auto-green#73]
这里是错误反馈
![image](https://user-images.githubusercontent.com/130721000/232388605-d23c21d5-20af-4dac-ab5e-d19959863ad6.png)
main a964630] a commit a day keeps your girlfriend away
11
remote: Permission to wuhu201314/sesese.git denied to github-actions[bot].
12
fatal: unable to access 'https://github.com/wuhu201314/sesese/': The requested URL returned error: 403
13
Error: Process completed with exit code 128.

**Comment by looking-at-the-stars** [comment]
好像打开Settings->Actions->General->Workflow permissions里面的Allow GitHub Actions to create and approve pull requests就好了

**Comment by so1ve** [comment]
建议迷渡在workflow里头加入permissions

**Comment by justjavac** [comment]
@so1ve #84
